[package]
name = "helper"
version = "0.1.0"
edition = "2021"

[dependencies]
fantoccini = "0.19.3"
regex = "1.7.0"
tokio = { version = "1.23.0", features = ["full"] }
urlencoding = "2.1.2"
chrono = "0.4.23"
